NitStore/Models/Domain/Category.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace NitStore.Models.Domain
{
    [Table("Category")]
    public class Category
    {
        [Key]
        [Column(Order = 0)]
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }
        [Required]
        [StringLength(255)]
        public string Description { get; set; }
    }
}

NitStore/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using NitStore.Data;
using NitStore.Models.Domain;

namespace NitStore.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly NitDbContext dbContext;

        public CategoriesController(NitDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            if (!(TempData["shortMessage"] ?? "").ToString().IsNullOrEmpty())
            {
                ViewBag.Message = TempData["shortMessage"].ToString();
            }
            return View(await dbContext.categories.ToListAsync());
        }

        public async Task<IActionResult> ViewAllCategory()
        {
            return View("ViewAllCategory",await dbContext.categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || dbContext.categories == null)
            {
                return NotFound();
            }

            var category = await dbContext.categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        
        public async Task<IActionResult> Create(Category category)
        {
            if (ModelState.IsValid)
            {
                bool result = await AddCategory(category);
                if(result == true)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(category);
        }

        public async Task<bool> AddCategory(Category category)
        {
            if (category == null)
            {
                return false;
            } else if (category.Name == null || category.Description == null)
            {
                return false;
            } else if (category.Name.Trim() == "" || category.Description.Trim() == "") 
            {
                return false;
            } else
            {
                dbContext.Add(category);
                await dbContext.SaveChangesAsync();
                return true;
            }
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || dbContext.categories == null)
            {
                return NotFound();
            }

            var category = await dbContext.categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        
        public async Task<IActionResult> Edit(int id, Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                Category result = await EditCategory(category);
                if(result != null)
                {
                    return RedirectToAction(nameof(Index));
                } else
                {
                    return NotFound();
                }
                
            }
            return View(category);
        }

        public async Task<Category> EditCategory(Category category)
        {
            try
            {
                dbContext.Update(category);
                await dbContext.SaveChangesAsync();
                return category;
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CategoryExists(category.Id))
                {
                    return null;
                }
                else
                {
                    return null;
                }
            }
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || dbContext.categories == null)
            {
                return NotFound();
            }

            var category = await dbContext.categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (dbContext.categories == null)
            {
                return Problem("Entity set 'NitdbContext.categories'  is null.");
            }
            var category = await dbContext.categories.FindAsync(id);
            if (category != null)
            {
                Product p = dbContext.products.Where(p => p.Category == id).FirstOrDefault();
                if (p != null)
                {
                    TempData["shortMessage"] = "Cannot Delete Category because still in use";
                    return RedirectToAction("Index");
                }
                dbContext.categories.Remove(category);
            }
            TempData["shortMessage"] = "Delete Category Success";
            await dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return dbContext.categories.Any(e => e.Id == id);
        }
    }
}

NitStore/Views/Categories/Create.cshtml
@model NitStore.Models.Domain.Category
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_LayoutMaketer";
}

<div class="container">
    <div class="d-flex container-fluid justify-content-center">
        <div class="w-75 mt-5">
            <h1>Add new category</h1>
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

NitStore/Views/Categories/Delete.cshtml
@model NitStore.Models.Domain.Category
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_LayoutMaketer";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>


<div class="container">
    <h3>Are you sure you want to delete this?</h3>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

NitStore/Views/Categories/Details.cshtml
@model NitStore.Models.Domain.Category
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_LayoutMaketer";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div class="container">
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    <div class="my-3">
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</div>

</body>
</html>

NitStore/Views/Categories/Edit.cshtml
@model NitStore.Models.Domain.Category
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_LayoutMaketer";
}

<div class="d-flex container justify-content-center">
    <div class="w-75 mt-5">
        <h1>Update Category</h1>
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

NitStore/Views/Categories/Index.cshtml
@model IEnumerable<NitStore.Models.Domain.Category>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_LayoutMaketer";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="container">
        <div>
            @if (ViewBag.Message != null)
            {
                <a>@ViewBag.Message !</a>
            }
        </div>
        <p>
            <a asp-action="Create">Create New</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
                <a asp-action="HomeMaketer" asp-controller="Home">  Back to List</a>
            </tbody>
        </table>
    </div>
</body>
</html>

NitStore/Views/Categories/ViewAllCategory.cshtml
@model IEnumerable<NitStore.Models.Domain.Category>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = "_LayoutMaketer";
}

<div class="d-flex container-fluid justify-content-center">
    <div class="w-75 mt-5">
        <button type="submit" class="btn btn-success" asp-controller="Categories" asp-action="Create" onclick="window.location.href='@Url.Action("Create", "Categories")'">Add Category</button>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
                <a asp-action="HomeMaketer" asp-controller="Home">  Back to List</a>
            </tbody>
        </table>
    </div>
</div>