NitStore/Controllers/AuthenController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NitStore.Data;
using NitStore.Models.Domain;
using NitStore.Models.DTO;

namespace NitStore.Controllers
{
    public class AuthenController : Controller
    {
        private readonly NitDbContext dbContext;
        public AuthenController(NitDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(User loginUser)
        {
            if (loginUser != null)
            {
                string username = loginUser.UserName;
                string password = EncryptPassword(loginUser.Password);
                var user = await dbContext.users.Where(u => u.UserName.Equals(username) && u.Password.Equals(password)).FirstOrDefaultAsync();
                if (user != null)
                {
                    if (user.Status == 0)
                    {

                    }
                    else 
                    {
                        string action = "";
                        string method = "";
                        switch(user.Role)
                        {
                            case 1:
                                method = "ViewAllUser";
                                action = "Users";
                                break;
                            case 2:
                                method = "Index";
                                action = "Categories";
                                break;
                            case 3:
                                method = "Index";
                                action = "Campaigns";
                                break;
                            case 4:
                                method = "HomeSale";
                                action = "Home";
                                break;
                            case 5:
                                method = "ListProduct";
                                action = "Products";
                                var userDetail = dbContext.userDetail.Where(ud => ud.Id == user.Id).FirstOrDefault();
                                if(userDetail != null)
                                {
                                    HttpContext.Session.SetString("Username", userDetail.Name);
                                }

                                break;

                        }
                        HttpContext.Session.SetString("UserId", user.Id + "");
                        HttpContext.Session.SetInt32("LoginRole", user.Role);
                        HttpContext.Session.SetInt32("isLogin", 1);
                        return RedirectToAction(method, action, new { area = "" });
                    }

                }else
                {
                    ViewBag.ErrorMessage = "Username or password invalid!";
                }
            }
            else
            {
                return View();
            }
            return View();

        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }

        [HttpGet]
        public async Task<IActionResult> Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterUserDTO user)
        {
            if(ModelState.IsValid)
            {
                if (user != null)
                {
                    if (user.Password.Equals(user.RePassword))
                    {
                        User newUser = new User
                        {
                            UserName = user.UserName,
                            Email = user.Email,
                            Password = EncryptPassword(user.Password),
                            Role = 5,
                            Status = 1
                        };
                        try
                        {
                            dbContext.users.Add(newUser);
                            await dbContext.SaveChangesAsync();
                            UserDetail userDetail = new UserDetail
                            {
                                Id = newUser.Id,
                                Name = user.Name,
                                Address = user.Address,
                                PhoneNumber = user.PhoneNumber,
                                Gender = user.Gender
                            };
                            dbContext.userDetail.Add(userDetail);
                            await dbContext.SaveChangesAsync();
                            return RedirectToAction("Login");
                        }
                        catch (Exception ex)
                        {
                            throw ex;
                            return View();
                        }
                    }
                    else
                    {
                        return View(user);
                    }
                }
                else
                {
                    return View();
                }
            } else
            {
                return View(user);
            }
            
        }

        private string EncryptPassword(string password)
        {
            string result = "";
            try
            {
                byte[] enCryptByte = new byte[password.Length];
                enCryptByte = System.Text.Encoding.UTF8.GetBytes(password);
                result = Convert.ToBase64String(enCryptByte);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
            return result;
        }
    }
}

NitStore/Views/Authen/Login.cshtml
@model NitStore.Models.Domain.User
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous" />
</head>
<body style="
      background-image: url('https://images.unsplash.com/photo-1587614382346-4ec70e388b28?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80');
      background-size: cover;
    ">
    <div class="container-fluid mh-100 d-flex align-items-center justify-content-center"
         style="height: 100vh">
        <div class="w-25 justify-content-center bg-light rounded">
            <div class="m-5">
                <div class="w-50 mx-auto bg-danger rounded text-light text-center"
                     style="margin-bottom: 30px">
                    <h3 class="p-1">NIT Shop</h3>
                </div>
                @using (Html.BeginForm("Login", "Authen", FormMethod.Post,
                new { enctype = "multipart/form-data" }))
                {
                    <div class="form-group">
                        <label asp-for="UserName" class="control-label"></label>
                        @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })

                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", type = "password"} })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                    <br />
                    <div class="m-auto text-center form-group">
                        <input type="submit" value="Login" class="btn btn-danger" />
                    </div>
                }
                @if (ViewBag.ErrorMessage != null) {
                    <p class="text-danger">@ViewBag.ErrorMessage</p>
                }
                <br />
                @Html.ActionLink("Click here to register", "Register", "Authen", new {}, null)
                
            </div>
        </div>
    </div>
    <footer style="position: fixed; bottom: 0; width: 100%"
            class="align-items-end bg-dark text-center text-white">
        <div class="container p-4">
            <section class="">
                <form action="">
                    <div class="row d-flex justify-content-center"></div>
                </form>
            </section>
            <section class="mb-4">
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt
                    distinctio earum repellat quaerat voluptatibus placeat nam, commodi
                    optio pariatur est quia magnam eum harum corrupti dicta, aliquam
                    sequi voluptate quas.
                </p>
            </section>
        </div>

        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
            © 2020 Copyright:
            <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
        </div>
    </footer>
</body>
</html>

NitStore/Views/Authen/Register.cshtml
@model NitStore.Models.DTO.RegisterUserDTO
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Register</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous" />
</head>
<body style="
      background-image: url('https://images.unsplash.com/photo-1587614382346-4ec70e388b28?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80');
      background-size: cover;
    ">
    <div class="container-fluid mh-100 d-flex align-items-center justify-content-center"
         style="height: 100vh">
        <div class="w-25 justify-content-center bg-light rounded">
            <div class="m-5">
                <div class="w-50 mx-auto bg-danger rounded text-light text-center"
                     style="margin-bottom: 30px">
                    <h3 class="p-1">Register</h3>
                </div>
                @using (Html.BeginForm("Register", "Authen", FormMethod.Post,
                new { enctype = "multipart/form-data" }))
                {
                    
                        
                        <div class="form-group">
                            <label asp-for="UserName" class="control-label"></label>
                            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                            
                        </div>
                        <div class="form-group">
                            <label asp-for="Password" class="control-label"></label>
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", type = "password" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label asp-for="RePassword" class="control-label"></label>
                        @Html.EditorFor(model => model.RePassword, new { htmlAttributes = new { @class = "form-control", type = "password" } })
                            @Html.ValidationMessageFor(model => model.RePassword, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label asp-for="Email" class="control-label"></label>
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label asp-for="Gender" class="control-label"></label>
                            @Html.CheckBoxFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })  Checked if male
                            @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label asp-for="PhoneNumber" class="control-label"></label>
                            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label asp-for="Address" class="control-label"></label>
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                        <br />
                        <div class="m-auto text-center form-group">
                            <input type="submit" value="Register" class="btn btn-danger" />
                        </div>
                    
                }
                <br />
                @Html.ActionLink("Click here to Login", "Login", "Authen", new {}, null)
            </div>
        </div>
    </div>
    @*<footer style="position: fixed; bottom: 0; width: 100%"
    class="align-items-end bg-dark text-center text-white">
    <div class="container p-4">
    <section class="">
    <form action="">
    <div class="row d-flex justify-content-center"></div>
    </form>
    </section>
    <section class="mb-4">
    <p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt
    distinctio earum repellat quaerat voluptatibus placeat nam, commodi
    optio pariatur est quia magnam eum harum corrupti dicta, aliquam
    sequi voluptate quas.
    </p>
    </section>
    </div>

    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    © 2020 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    </footer>*@
</body>
</html>