NitStore/Models/Domain/Feedback.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NitStore.Models.Domain
{
    [Table("Feedback")]
    public partial class Feedback
    {
        [Key]
        [Column(Order = 0)]
        public int Id { get; set; }

        [Required]
        [Column(Order = 1)]
        public int CustomerId { get; set; }

        [Required]
        [Column(Order = 2)]
        public int ProductId { get; set; }

        [Required]
        [StringLength(255)]
        public string Description { get; set; }

        [Required]
        public DateTime UpdatedDate { get; set; }

        public int OrderId { get; set; }

        public int Rate { get; set; }
    }
}

NitStore/Controllers/FeedbacksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NitStore.Data;
using NitStore.Models.Domain;
using NitStore.Models.DTO;

namespace NitStore.Controllers
{
    public class FeedbacksController : Controller
    {
        private readonly NitDbContext dbContext;

        public FeedbacksController(NitDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        // GET: Feedbacks
        public async Task<IActionResult> Index()
        {
              return View(await dbContext.feedbacks.ToListAsync());
        }

        // GET: Feedbacks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || dbContext.feedbacks == null)
            {
                return NotFound();
            }

            var feedback = await dbContext.feedbacks
                .FirstOrDefaultAsync(m => m.Id == id);
            if (feedback == null)
            {
                return NotFound();
            }

            return View(feedback);
        }

        // GET: Feedbacks/Create
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult FeedbackOrder(int orderId)
        {
            int userId = -1;
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
            {
                userId = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
            }
            else
            {
                return RedirectToAction("Login", "Authen");
            }
            Order order = dbContext.orders.Where(x => x.Id == orderId).FirstOrDefault();
            List<OrderDetail > orderDetail = new List<OrderDetail>();
            List<FeedbackOrderDTO> feedbacks = new List<FeedbackOrderDTO>();
            if (order != null)
            {
                orderDetail = dbContext.ordersDetail.Where(x => x.OrderId == orderId).ToList();

                foreach (OrderDetail item in orderDetail)
                {
                    ProductImage productImage = dbContext.productsImage.Where(x => x.ProductId == item.ProductId).First();
                    Product p = dbContext.products.Where(x => x.Id == item.ProductId).FirstOrDefault();
                    Image image = dbContext.images.Where(x => x.Id == productImage.ImageId).First();
                    FeedbackOrderDTO dto = new FeedbackOrderDTO()
                    {
                        imageBit = image.ImageData,
                        ProductId = item.ProductId,
                        ProductName = p.Name,
                        CustomerId = userId,
                        feedback = "",
                        OrderID = order.Id
                    };
                    feedbacks.Add(dto);
                }
            }
            ViewBag.Feedbacks = feedbacks;
            return View(feedbacks);
        }
        [HttpPost]
        public IActionResult FeedbackOrder(List<FeedbackOrderDTO> feedbacks)
        {
            foreach(FeedbackOrderDTO dto in feedbacks)
            {
                Feedback f = new Feedback()
                {
                    ProductId = dto.ProductId,
                    CustomerId = dto.CustomerId,
                    Description = dto.feedback,
                    UpdatedDate = DateTime.Now,
                    OrderId = dto.OrderID,
                    Rate = dto.Rate
                };
                dbContext.feedbacks.Add(f);
                dbContext.SaveChanges();
            }
            TempData["shortMessage"] = "Feedback Success";
            return RedirectToAction("OrderHistory", "Orders");
        }
        // POST: Feedbacks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        
        public async Task<IActionResult> Create(Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                AddFeedback(feedback);
                return RedirectToAction(nameof(Index));
            }
            return View(feedback);
        }

        public async Task<bool> AddFeedback(Feedback feedback)
        {
            dbContext.Add(feedback);
            await dbContext.SaveChangesAsync();
            return true;
        }


        // GET: Feedbacks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || dbContext.feedbacks == null)
            {
                return NotFound();
            }

            var feedback = await dbContext.feedbacks.FindAsync(id);
            if (feedback == null)
            {
                return NotFound();
            }
            return View(feedback);
        }

        // POST: Feedbacks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        
        public async Task<IActionResult> Edit(int id, Feedback feedback)
        {
            if (id != feedback.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    dbContext.Update(feedback);
                    await dbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FeedbackExists(feedback.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(feedback);
        }

        // GET: Feedbacks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || dbContext.feedbacks == null)
            {
                return NotFound();
            }

            var feedback = await dbContext.feedbacks
                .FirstOrDefaultAsync(m => m.Id == id);
            if (feedback == null)
            {
                return NotFound();
            }

            return View(feedback);
        }

        // POST: Feedbacks/Delete/5
        [HttpPost, ActionName("Delete")]
        
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (dbContext.feedbacks == null)
            {
                return Problem("Entity set 'NitDbContext.feedbacks'  is null.");
            }
            var feedback = await dbContext.feedbacks.FindAsync(id);
            if (feedback != null)
            {
                dbContext.feedbacks.Remove(feedback);
            }
            
            await dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FeedbackExists(int id)
        {
          return dbContext.feedbacks.Any(e => e.Id == id);
        }
    }
}

NitStore/Views/Feedbacks/Create.cshtml
@model NitStore.Models.Domain.Feedback
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>Feedback</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <input asp-for="CustomerId" class="form-control" />
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <input asp-for="ProductId" class="form-control" />
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedDate" class="control-label"></label>
                <input asp-for="UpdatedDate" class="form-control" />
                <span asp-validation-for="UpdatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

NitStore/Views/Feedbacks/Delete.cshtml
@model NitStore.Models.Domain.Feedback
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Feedback</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

NitStore/Views/Feedbacks/Details.cshtml
@model NitStore.Models.Domain.Feedback
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>Feedback</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

NitStore/Views/Feedbacks/Edit.cshtml
@model NitStore.Models.Domain.Feedback
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>Feedback</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <input asp-for="CustomerId" class="form-control" />
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <input asp-for="ProductId" class="form-control" />
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedDate" class="control-label"></label>
                <input asp-for="UpdatedDate" class="form-control" />
                <span asp-validation-for="UpdatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

NitStore/Views/Feedbacks/FeedbackOrder.cshtml
@model List<NitStore.Models.DTO.FeedbackOrderDTO>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "~/shared/_LayoutShop.cshtml";
}

@using (Html.BeginForm("FeedbackOrder", "Feedbacks", FormMethod.Post,
                             new { enctype = "multipart/form-data" }))
{

    <div class="d-flex container-fluid justify-content-center">
        <div class="w-75 mt-5">
            <h1>Add feedback for Order</h1>
            @for (var i = 0; i < @Model.Count; i++){
                @Html.HiddenFor(model => model[i].OrderID)
                @Html.HiddenFor(model => model[i].ProductId)
                @Html.HiddenFor(model => model[i].CustomerId)
                <div class="col-md-2 col-lg-2 col-xl-2">
                    <img src="data:image;base64,@System.Convert.ToBase64String(@Model[i].imageBit)"
                 class="img-fluid rounded-3"
                 alt="" />
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-default">@Model[i].ProductName</span>
                    @Html.EditorFor(model => model[i].feedback, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-default">Rating</span>
                    @Html.EditorFor(model => model[i].Rate, new { htmlAttributes = new { @class = "form-control", min = 0, max = 5 } })
                </div>
            }
            



            <div class="form-group btn-create">
                <div>
                    <input type="submit" value="Add Feedback" class=" btn btn-warning btn-normal" />
                    @*<span style="color: @TempData["Color"]">
                @TempData["Message"]
                </span>
                <span style="color: @TempData["Color"]">
                @TempData["SuccessMessage"]
                </span>
                <span style="color: @TempData["Color"]">
                @TempData["ErrorMessage"]
                </span>*@
                </div>
            </div>
        </div>
    </div>
}

NitStore/Views/Feedbacks/Index.cshtml
@model IEnumerable<NitStore.Models.Domain.Feedback>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UpdatedDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</body>
</html>